#!/bin/bash
#
###
# Portal service. {start, stop}
#
#
# 2015/03/31    hayate
set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
TWISTD=/usr/bin/twistd
# PYTHON=/usr/local/python-2.7.9/bin/python
PYTHON=/usr/bin/python2.7

LOG_PATH=/siov/opt/bidong/logs/radiusd
PID_PATH=/siov/opt/bidong/run

RADIUS_PATH=/web/radius
RADIUS_APP=$RADIUS_PATH/auth_radius.py
RADIUS_PID=$PID_PATH/auth_radius.pid

DESC=auth_radius

# test -x $TWISTD || exit 1
test -x $PYTHON || exit 1

# create necessary logs directory
if [ ! -d $LOG_PATH ]; then
    mkdir $LOG_PATH
fi
if [ ! -d $PID_PATH ]; then
    mkdir $PID_PATH
fi

case "$1" in
    start)
        echo "Starting $DESC service: "
        cd $RADIUS_PATH
        $PYTHON $RADIUS_APP > /dev/null 2>&1 &
        echo "$DESC."
        ;;
    stop)
        echo "Stop $DESC service: "
        kill -s HUP $(cat $RADIUS_PID) && rm -f $RADIUS_PID
        echo "$DESC stoped."
        ;;
    *)
        echo "Usage: $DESC {start|stop}"
        exit 1
        ;;
esac
exit 0

