#!/bin/bash
#
###
# Portal service. {start, stop}
#
#
# 2015/03/31    hayate
set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
TWISTD=/usr/local/bin/twistd
PYTHON=/usr/bin/python3.5
LOG=/var/log/radiusd
RADIUS_PATH=/web/aaa
RADIUS_APP=$RADIUS_PATH/radius.py

PID_PATH=/var/run/radius
# RADIUS_PID=/var/run/radius.pid

DESC=radius

# test -x $TWISTD || exit 1
test -x $PYTHON || exit 1

# create necessary logs directory
if [ ! -d $LOG ]; then
    mkdir $LOG
fi

if [ ! -d $PID_PATH ]; then
    mkdir $PID_PATH
fi

case "$1" in
    start)
        echo "Starting $DESC service: "
        cd $RADIUS_PATH
        $PYTHON $RADIUS_APP > /dev/null 2>&1 &
        echo "$DESC."
        ;;
    stop)
        echo "Stop $DESC service: "
        files=$(ls $PID_PATH | grep ^radius_.*)
        echo $files
        for file in $files
        do
            echo "\tStop $file"
            set +e
            kill -s HUP $(cat $PID_PATH/$file) && rm -f $PID_PATH/$file
            set -e
            echo "$file."
        done
        echo "$DESC."
        ;;
    *)
        echo "Usage: $DESC {start|stop}"
        exit 1
        ;;
esac
exit 0

